version: "3.9"

services:
  database_ignite:
    image: postgres
    container_name: datebase_fin_api
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fin_db
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: fin_api
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database_ignite
    depends_on:
      - database_ignite
volumes:
  pgdata:
    driver: local
